# Generated by Django 4.0.2 on 2022-02-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mouse',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teclado',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
